name = "chat-worker" # Worker 的名字
main = "src/index.js"
compatibility_date = "2024-05-15"

# 绑定 Vectorize 和 AI
[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "my-rag-index"

[ai]
binding = "AI"

# 重要：将 GitHub Secret 绑定到 Worker 的环境变量
[vars]
# 这里不需要直接写 OPENAI_API_KEY，我们将在 GitHub Actions 中处理
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



